### ISSUE TITLE
How to set permanent named volumes for Postgres database?

### ISSUE THREAD

**Issue by poVoq** [sn0w/pleroma-docker#3]
It looks like the install script also loads it's own postgres image, or at least it is included?
For data security and easier administration: how is the volume for "/var/lib/postgresql/data" created and can it be stored as a named volume?

**Comment by sn0w** [comment]
All data is stored in the folder specified by `DOCKER_DATADIR`.
In this example `/var/lib/postgresql/data` will be a mount of `$DOCKER_DATADIR/db`.
Named volumes are currently not supported.

The postgres image is from https://hub.docker.com/_/postgres/
